<?php

namespace Database\Seeders;

use App\Enums\FoodCategory;
use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Food::query()
            ->whereIn('slug', [
                'crispy-rice-chicken',
                'double-sizzle-burger',
                'golden-fries-cup',
                'chili-lime-nuggets',
                'garden-egg-wrap',
                'iced-citrus-tea',
                'berry-fizz',
                'vietnamese-iced-coffee',
                'mango-yogurt-shake',
                'sparkling-lychee',
            ])
            ->delete();

        collect([
            [
                'menu_code' => 'pho_bo_01',
                'name' => 'Beef Pho',
                'vietnamese_name' => 'Phở Bò',
                'category' => FoodCategory::Food,
                'description' => 'Traditional Vietnamese beef noodle soup with herbs and rice noodles',
                'vietnamese_description' => 'Phở bò truyền thống với rau thơm và bánh phở',
                'subcategory' => 'noodle soup',
                'protein' => 'beef',
                'cooking_style' => 'boiled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 2,
                'richness' => 1,
                'temperature' => 'hot',
                'texture' => 'soft,chewy',
                'vegetarian' => false,
                'contains_pork' => false,
                'contains_beef' => true,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => false,
                'halal_friendly' => false,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'breakfast',
                'keywords' => 'herbal,light,classic,comforting',
                'recommendation_reason' => 'A light and comforting Vietnamese classic that is beginner friendly',
                'price_vnd' => 65000,
                'image_path' => 'menu/pho-bo.png',
            ],
            [
                'menu_code' => 'banh_mi_01',
                'name' => 'Vietnamese Baguette Sandwich',
                'vietnamese_name' => 'Bánh Mì',
                'category' => FoodCategory::Food,
                'description' => 'Vietnamese baguette sandwich with meat and pickled vegetables',
                'vietnamese_description' => 'Bánh mì Việt Nam với thịt và rau củ ngâm chua',
                'subcategory' => 'street food',
                'protein' => 'pork',
                'cooking_style' => 'fresh',
                'sweetness' => 1,
                'spiciness' => 1,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 2,
                'temperature' => 'warm',
                'texture' => 'crispy,juicy',
                'vegetarian' => false,
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => false,
                'halal_friendly' => false,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'lunch',
                'keywords' => 'crispy,savory,portable,street food',
                'recommendation_reason' => 'Perfect for a quick and flavorful Vietnamese street food experience',
                'price_vnd' => 30000,
                'image_path' => 'menu/banh-mi.png',
            ],
            [
                'menu_code' => 'bun_bo_hue_01',
                'name' => 'Hue Beef Noodle Soup',
                'vietnamese_name' => 'Bún Bò Huế',
                'category' => FoodCategory::Food,
                'description' => 'Spicy central Vietnamese beef noodle soup',
                'vietnamese_description' => 'Bún bò miền Trung cay nồng',
                'subcategory' => 'noodle soup',
                'protein' => 'beef',
                'cooking_style' => 'boiled',
                'sweetness' => 0,
                'spiciness' => 3,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 3,
                'temperature' => 'hot',
                'texture' => 'chewy,rich',
                'vegetarian' => false,
                'contains_pork' => false,
                'contains_beef' => true,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => false,
                'halal_friendly' => false,
                'beginner_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => true,
                'healthy' => false,
                'comfort_food' => true,
                'quick_meal' => false,
                'heavy_meal' => true,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'lunch',
                'keywords' => 'spicy,rich,bold,central vietnam',
                'recommendation_reason' => 'A bold and spicy noodle soup for users seeking strong Vietnamese flavors',
                'price_vnd' => 70000,
                'image_path' => 'menu/bun-bo-hue.png',
            ],
            [
                'menu_code' => 'mi_quang_01',
                'name' => 'Quang-Style Turmeric Noodles',
                'vietnamese_name' => 'Mì Quảng',
                'category' => FoodCategory::Food,
                'description' => 'Central Vietnamese turmeric noodles with herbs, peanuts, and pork broth',
                'vietnamese_description' => 'Mì Quảng miền Trung với nghệ, rau thơm, đậu phộng và nước dùng heo',
                'subcategory' => 'noodle soup',
                'protein' => 'pork',
                'cooking_style' => 'boiled',
                'sweetness' => 1,
                'spiciness' => 1,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 2,
                'temperature' => 'warm',
                'texture' => 'chewy,crunchy',
                'vegetarian' => false,
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => true,
                'contains_dairy' => false,
                'halal_friendly' => false,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => true,
                'healthy' => false,
                'comfort_food' => true,
                'quick_meal' => false,
                'heavy_meal' => true,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'lunch',
                'keywords' => 'turmeric,herbal,central vietnam,rich',
                'recommendation_reason' => 'A flavorful central Vietnamese noodle dish with rich textures and herbs',
                'price_vnd' => 65000,
                'image_path' => 'menu/mi-quang.png',
            ],
            [
                'menu_code' => 'com_tam_01',
                'name' => 'Broken Rice with Grilled Pork',
                'vietnamese_name' => 'Cơm Tấm',
                'category' => FoodCategory::Food,
                'description' => 'Broken rice served with grilled pork, egg, and fish sauce',
                'vietnamese_description' => 'Cơm tấm ăn kèm sườn nướng, trứng và nước mắm',
                'subcategory' => 'rice dish',
                'protein' => 'pork,egg',
                'cooking_style' => 'grilled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 2,
                'richness' => 2,
                'temperature' => 'hot',
                'texture' => 'juicy,soft',
                'vegetarian' => false,
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => false,
                'halal_friendly' => false,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => true,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'lunch',
                'keywords' => 'grilled,savory,saigon classic,comforting',
                'recommendation_reason' => 'A classic Saigon comfort meal loved by both locals and tourists',
                'price_vnd' => 55000,
                'image_path' => 'menu/com-tam.png',
            ],
            [
                'menu_code' => 'bun_cha_01',
                'name' => 'Hanoi Grilled Pork with Vermicelli',
                'vietnamese_name' => 'Bún Chả',
                'category' => FoodCategory::Food,
                'description' => 'Hanoi grilled pork with noodles, herbs, and dipping sauce',
                'vietnamese_description' => 'Bún chả Hà Nội với thịt heo nướng, rau thơm và nước chấm',
                'subcategory' => 'grilled dish',
                'protein' => 'pork',
                'cooking_style' => 'grilled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 1,
                'temperature' => 'warm',
                'texture' => 'juicy,fresh',
                'vegetarian' => false,
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => false,
                'halal_friendly' => false,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => true,
                'price_range' => 'medium',
                'best_time' => 'lunch',
                'keywords' => 'hanoi,grilled,fresh,balanced',
                'recommendation_reason' => 'A balanced and beginner friendly Hanoi specialty with grilled flavors',
                'price_vnd' => 65000,
                'image_path' => 'menu/bun-cha.png',
            ],
            [
                'menu_code' => 'hu_tieu_01',
                'name' => 'Southern Vietnamese Noodle Soup',
                'vietnamese_name' => 'Hủ Tiếu',
                'category' => FoodCategory::Food,
                'description' => 'Southern Vietnamese noodle soup with pork and seafood broth',
                'vietnamese_description' => 'Hủ tiếu miền Nam với thịt heo và nước dùng hải sản',
                'subcategory' => 'noodle soup',
                'protein' => 'pork,seafood',
                'cooking_style' => 'boiled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 2,
                'richness' => 1,
                'temperature' => 'hot',
                'texture' => 'soft,chewy',
                'vegetarian' => false,
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => true,
                'contains_nuts' => false,
                'contains_dairy' => false,
                'halal_friendly' => false,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'breakfast',
                'keywords' => 'southern vietnam,light,noodle soup,comforting',
                'recommendation_reason' => 'A light and comforting southern Vietnamese noodle soup perfect for casual meals',
                'price_vnd' => 50000,
                'image_path' => 'menu/hu-tieu.png',
            ],
            [
                'menu_code' => 'ca_phe_sua_da_01',
                'name' => 'Vietnamese Iced Coffee',
                'vietnamese_name' => 'Cà Phê Đá',
                'category' => FoodCategory::Drink,
                'description' => 'Strong Vietnamese coffee with condensed milk and ice',
                'vietnamese_description' => 'Cà phê Việt Nam đậm vị với sữa đặc và đá',
                'subcategory' => 'drink',
                'protein' => 'vegetarian',
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 1,
                'richness' => 3,
                'temperature' => 'cold',
                'texture' => 'creamy,strong',
                'vegetarian' => true,
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => true,
                'halal_friendly' => true,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'anytime',
                'keywords' => 'coffee,strong,sweet,energizing',
                'recommendation_reason' => 'A bold and sweet Vietnamese coffee experience popular with tourists',
                'price_vnd' => 35000,
                'image_path' => 'menu/vietnamese-iced-coffee.png',
            ],
            [
                'menu_code' => 'bac_xiu_01',
                'name' => 'Vietnamese Sweet Milk Coffee',
                'vietnamese_name' => 'Bạc Xỉu',
                'category' => FoodCategory::Drink,
                'description' => 'Sweet Vietnamese milk coffee with a lighter coffee flavor',
                'vietnamese_description' => 'Bạc xỉu ngọt béo với vị cà phê nhẹ',
                'subcategory' => 'drink',
                'protein' => 'vegetarian',
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 1,
                'richness' => 2,
                'temperature' => 'cold',
                'texture' => 'creamy,smooth',
                'vegetarian' => true,
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => true,
                'halal_friendly' => true,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'anytime',
                'keywords' => 'sweet,milky,coffee,gentle',
                'recommendation_reason' => 'A sweeter and lighter coffee choice ideal for beginners',
                'price_vnd' => 35000,
                'image_path' => 'menu/bac-xiu.png',
            ],
            [
                'menu_code' => 'tra_sua_tran_chau_01',
                'name' => 'Bubble Milk Tea',
                'vietnamese_name' => 'Trà Sữa Trân Châu',
                'category' => FoodCategory::Drink,
                'description' => 'Milk tea with chewy tapioca pearls',
                'vietnamese_description' => 'Trà sữa với trân châu dai',
                'subcategory' => 'drink',
                'protein' => 'vegetarian',
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 1,
                'richness' => 2,
                'temperature' => 'cold',
                'texture' => 'chewy,creamy',
                'vegetarian' => true,
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => true,
                'halal_friendly' => true,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => true,
                'price_range' => 'medium',
                'best_time' => 'snack',
                'keywords' => 'bubble tea,sweet,trendy,chewy',
                'recommendation_reason' => 'A fun and sweet drink with chewy pearls loved by younger customers',
                'price_vnd' => 50000,
                'image_path' => 'menu/bubble-milk-tea.png',
            ],
            [
                'menu_code' => 'matcha_latte_01',
                'name' => 'Matcha Latte',
                'vietnamese_name' => 'Matcha Latte',
                'category' => FoodCategory::Drink,
                'description' => 'Creamy green tea latte with earthy matcha flavor',
                'vietnamese_description' => 'Latte trà xanh béo mịn với vị matcha thanh đất',
                'subcategory' => 'drink',
                'protein' => 'vegetarian',
                'cooking_style' => 'fresh',
                'sweetness' => 2,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 0,
                'richness' => 2,
                'temperature' => 'cold',
                'texture' => 'creamy,smooth',
                'vegetarian' => true,
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => true,
                'halal_friendly' => true,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'comfort_food' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'anytime',
                'keywords' => 'matcha,earthy,creamy,trendy',
                'recommendation_reason' => 'A smooth and modern green tea drink popular among cafe visitors',
                'price_vnd' => 55000,
                'image_path' => 'menu/matcha-latte.png',
            ],
            [
                'menu_code' => 'nuoc_mia_01',
                'name' => 'Sugarcane Juice',
                'vietnamese_name' => 'Nước Mía',
                'category' => FoodCategory::Drink,
                'description' => 'Fresh pressed sugarcane juice served with ice',
                'vietnamese_description' => 'Nước mía ép tươi dùng với đá',
                'subcategory' => 'drink',
                'protein' => 'vegetarian',
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 0,
                'richness' => 0,
                'temperature' => 'cold',
                'texture' => 'refreshing,light',
                'vegetarian' => true,
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'contains_dairy' => false,
                'halal_friendly' => true,
                'beginner_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'comfort_food' => false,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => true,
                'price_range' => 'low',
                'best_time' => 'afternoon',
                'keywords' => 'refreshing,natural,sweet,tropical',
                'recommendation_reason' => 'A refreshing tropical street drink perfect for hot Vietnamese weather',
                'price_vnd' => 25000,
                'image_path' => 'menu/sugarcane-juice.png',
            ],
        ])->each(function (array $food, int $index): void {
            $food['ingredients'] = $food['description'];

            Food::updateOrCreate(
                ['menu_code' => $food['menu_code']],
                [
                    ...$food,
                    'slug' => str($food['name'])->slug()->toString(),
                    'is_available' => true,
                    'sort_order' => $index + 1,
                ],
            );
        });
    }
}
