<?php

namespace Database\Seeders;

use App\Enums\FoodCategory;
use App\Enums\FoodTaste;
use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Food::query()
            ->whereIn('slug', [
                'crispy-rice-chicken',
                'double-sizzle-burger',
                'golden-fries-cup',
                'chili-lime-nuggets',
                'garden-egg-wrap',
                'iced-citrus-tea',
                'berry-fizz',
                'vietnamese-iced-coffee',
                'mango-yogurt-shake',
                'sparkling-lychee',
            ])
            ->delete();

        collect([
            [
                'menu_code' => 'pho_bo_01',
                'name' => 'Beef Pho',
                'vietnamese_name' => 'Phở Bò',
                'category' => FoodCategory::Food,
                'description' => 'Traditional Vietnamese beef noodle soup with herbs and rice noodles',
                'vietnamese_description' => 'Phở bò truyền thống với rau thơm và bánh phở',
                'subcategory' => 'noodle soup',
                'protein' => 'beef',
                'cooking_style' => 'boiled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 2,
                'richness' => 1,
                'temperature' => 'hot',
                'texture' => 'soft,chewy',
                'contains_pork' => false,
                'contains_beef' => true,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'breakfast',
                'keywords' => 'herbal,light,classic,aromatic',
                'recommendation_reason' => 'A light and aromatic Vietnamese classic with familiar flavors',
                'price_vnd' => 65000,
                'image_path' => 'menu/pho-bo.png',
            ],
            [
                'menu_code' => 'banh_mi_01',
                'name' => 'Vietnamese Baguette Sandwich',
                'vietnamese_name' => 'Bánh Mì',
                'category' => FoodCategory::Food,
                'description' => 'Vietnamese baguette sandwich with meat and pickled vegetables',
                'vietnamese_description' => 'Bánh mì Việt Nam với thịt và rau củ ngâm chua',
                'subcategory' => 'street food',
                'protein' => 'pork',
                'cooking_style' => 'fresh',
                'sweetness' => 1,
                'spiciness' => 1,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 2,
                'temperature' => 'warm',
                'texture' => 'crispy,juicy',
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'lunch',
                'keywords' => 'crispy,savory,portable,street food',
                'recommendation_reason' => 'Perfect for a quick and flavorful Vietnamese street food experience',
                'price_vnd' => 30000,
                'image_path' => 'menu/banh-mi.png',
            ],
            [
                'menu_code' => 'bun_bo_hue_01',
                'name' => 'Hue Beef Noodle Soup',
                'vietnamese_name' => 'Bún Bò Huế',
                'category' => FoodCategory::Food,
                'description' => 'Spicy central Vietnamese beef noodle soup',
                'vietnamese_description' => 'Bún bò miền Trung cay nồng',
                'subcategory' => 'noodle soup',
                'protein' => 'beef',
                'cooking_style' => 'boiled',
                'sweetness' => 0,
                'spiciness' => 3,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 3,
                'temperature' => 'hot',
                'texture' => 'chewy,rich',
                'contains_pork' => false,
                'contains_beef' => true,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => true,
                'healthy' => false,
                'quick_meal' => false,
                'heavy_meal' => true,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'lunch',
                'keywords' => 'spicy,rich,bold,central vietnam',
                'recommendation_reason' => 'A bold and spicy noodle soup for users seeking strong Vietnamese flavors',
                'price_vnd' => 70000,
                'image_path' => 'menu/bun-bo-hue.png',
            ],
            [
                'menu_code' => 'mi_quang_01',
                'name' => 'Quang-Style Turmeric Noodles',
                'vietnamese_name' => 'Mì Quảng',
                'category' => FoodCategory::Food,
                'description' => 'Central Vietnamese turmeric noodles with herbs, peanuts, and pork broth',
                'vietnamese_description' => 'Mì Quảng miền Trung với nghệ, rau thơm, đậu phộng và nước dùng heo',
                'subcategory' => 'noodle soup',
                'protein' => 'pork',
                'cooking_style' => 'boiled',
                'sweetness' => 1,
                'spiciness' => 1,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 2,
                'temperature' => 'warm',
                'texture' => 'chewy,crunchy',
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => true,
                'halal_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => true,
                'healthy' => false,
                'quick_meal' => false,
                'heavy_meal' => true,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'lunch',
                'keywords' => 'turmeric,herbal,central vietnam,rich',
                'recommendation_reason' => 'A flavorful central Vietnamese noodle dish with rich textures and herbs',
                'price_vnd' => 65000,
                'image_path' => 'menu/mi-quang.png',
            ],
            [
                'menu_code' => 'com_tam_01',
                'name' => 'Broken Rice with Grilled Pork',
                'vietnamese_name' => 'Cơm Tấm',
                'category' => FoodCategory::Food,
                'description' => 'Broken rice served with grilled pork, egg, and fish sauce',
                'vietnamese_description' => 'Cơm tấm ăn kèm sườn nướng, trứng và nước mắm',
                'subcategory' => 'rice dish',
                'protein' => 'pork,egg',
                'cooking_style' => 'grilled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 2,
                'richness' => 2,
                'temperature' => 'hot',
                'texture' => 'juicy,soft',
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'quick_meal' => true,
                'heavy_meal' => true,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'lunch',
                'keywords' => 'grilled,savory,saigon classic,rich',
                'recommendation_reason' => 'A classic Saigon rice plate loved by both locals and tourists',
                'price_vnd' => 55000,
                'image_path' => 'menu/com-tam.png',
            ],
            [
                'menu_code' => 'bun_cha_01',
                'name' => 'Hanoi Grilled Pork with Vermicelli',
                'vietnamese_name' => 'Bún Chả',
                'category' => FoodCategory::Food,
                'description' => 'Hanoi grilled pork with noodles, herbs, and dipping sauce',
                'vietnamese_description' => 'Bún chả Hà Nội với thịt heo nướng, rau thơm và nước chấm',
                'subcategory' => 'grilled dish',
                'protein' => 'pork',
                'cooking_style' => 'grilled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 1,
                'saltiness' => 2,
                'richness' => 1,
                'temperature' => 'warm',
                'texture' => 'juicy,fresh',
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => true,
                'price_range' => 'medium',
                'best_time' => 'lunch',
                'keywords' => 'hanoi,grilled,fresh,balanced',
                'recommendation_reason' => 'A balanced Hanoi specialty with grilled flavors',
                'price_vnd' => 65000,
                'image_path' => 'menu/bun-cha.png',
            ],
            [
                'menu_code' => 'hu_tieu_01',
                'name' => 'Southern Vietnamese Noodle Soup',
                'vietnamese_name' => 'Hủ Tiếu',
                'category' => FoodCategory::Food,
                'description' => 'Southern Vietnamese noodle soup with pork and seafood broth',
                'vietnamese_description' => 'Hủ tiếu miền Nam với thịt heo và nước dùng hải sản',
                'subcategory' => 'noodle soup',
                'protein' => 'pork,seafood',
                'cooking_style' => 'boiled',
                'sweetness' => 1,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 2,
                'richness' => 1,
                'temperature' => 'hot',
                'texture' => 'soft,chewy',
                'contains_pork' => true,
                'contains_beef' => false,
                'contains_seafood' => true,
                'contains_nuts' => false,
                'halal_friendly' => false,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'breakfast',
                'keywords' => 'southern vietnam,light,noodle soup,savory',
                'recommendation_reason' => 'A light and savory southern Vietnamese noodle soup perfect for casual meals',
                'price_vnd' => 50000,
                'image_path' => 'menu/hu-tieu.png',
            ],
            [
                'menu_code' => 'ca_phe_sua_da_01',
                'name' => 'Vietnamese Iced Coffee',
                'vietnamese_name' => 'Cà Phê Đá',
                'category' => FoodCategory::Drink,
                'description' => 'Strong Vietnamese coffee with condensed milk and ice',
                'vietnamese_description' => 'Cà phê Việt Nam đậm vị với sữa đặc và đá',
                'subcategory' => 'drink',
                'protein' => null,
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 1,
                'richness' => 3,
                'temperature' => 'cold',
                'texture' => 'creamy,strong',
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'anytime',
                'keywords' => 'coffee,strong,sweet,energizing',
                'recommendation_reason' => 'A bold and sweet Vietnamese coffee experience popular with tourists',
                'price_vnd' => 35000,
                'image_path' => 'menu/vietnamese-iced-coffee.png',
            ],
            [
                'menu_code' => 'bac_xiu_01',
                'name' => 'Vietnamese Sweet Milk Coffee',
                'vietnamese_name' => 'Bạc Xỉu',
                'category' => FoodCategory::Drink,
                'description' => 'Sweet Vietnamese milk coffee with a lighter coffee flavor',
                'vietnamese_description' => 'Bạc xỉu ngọt béo với vị cà phê nhẹ',
                'subcategory' => 'drink',
                'protein' => null,
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 1,
                'richness' => 2,
                'temperature' => 'cold',
                'texture' => 'creamy,smooth',
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'low',
                'best_time' => 'anytime',
                'keywords' => 'sweet,milky,coffee,gentle',
                'recommendation_reason' => 'A sweeter and lighter coffee choice with a gentle coffee profile',
                'price_vnd' => 35000,
                'image_path' => 'menu/bac-xiu.png',
            ],
            [
                'menu_code' => 'tra_sua_tran_chau_01',
                'name' => 'Bubble Milk Tea',
                'vietnamese_name' => 'Trà Sữa Trân Châu',
                'category' => FoodCategory::Drink,
                'description' => 'Milk tea with chewy tapioca pearls',
                'vietnamese_description' => 'Trà sữa với trân châu dai',
                'subcategory' => 'drink',
                'protein' => null,
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 1,
                'richness' => 2,
                'temperature' => 'cold',
                'texture' => 'chewy,creamy',
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => false,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => true,
                'price_range' => 'medium',
                'best_time' => 'snack',
                'keywords' => 'bubble tea,sweet,trendy,chewy',
                'recommendation_reason' => 'A fun and sweet drink with chewy pearls loved by younger customers',
                'price_vnd' => 50000,
                'image_path' => 'menu/bubble-milk-tea.png',
            ],
            [
                'menu_code' => 'matcha_latte_01',
                'name' => 'Matcha Latte',
                'vietnamese_name' => 'Matcha Latte',
                'category' => FoodCategory::Drink,
                'description' => 'Creamy green tea latte with earthy matcha flavor',
                'vietnamese_description' => 'Latte trà xanh béo mịn với vị matcha thanh đất',
                'subcategory' => 'drink',
                'protein' => null,
                'cooking_style' => 'fresh',
                'sweetness' => 2,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 0,
                'richness' => 2,
                'temperature' => 'cold',
                'texture' => 'creamy,smooth',
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => false,
                'price_range' => 'medium',
                'best_time' => 'anytime',
                'keywords' => 'matcha,earthy,creamy,trendy',
                'recommendation_reason' => 'A smooth and modern green tea drink popular among cafe visitors',
                'price_vnd' => 55000,
                'image_path' => 'menu/matcha-latte.png',
            ],
            [
                'menu_code' => 'nuoc_mia_01',
                'name' => 'Sugarcane Juice',
                'vietnamese_name' => 'Nước Mía',
                'category' => FoodCategory::Drink,
                'description' => 'Fresh pressed sugarcane juice served with ice',
                'vietnamese_description' => 'Nước mía ép tươi dùng với đá',
                'subcategory' => 'drink',
                'protein' => null,
                'cooking_style' => 'fresh',
                'sweetness' => 3,
                'spiciness' => 0,
                'sourness' => 0,
                'saltiness' => 0,
                'richness' => 0,
                'temperature' => 'cold',
                'texture' => 'refreshing,light',
                'contains_pork' => false,
                'contains_beef' => false,
                'contains_seafood' => false,
                'contains_nuts' => false,
                'halal_friendly' => true,
                'tourist_favorite' => true,
                'adventurous' => false,
                'healthy' => true,
                'quick_meal' => true,
                'heavy_meal' => false,
                'shareable' => true,
                'price_range' => 'low',
                'best_time' => 'afternoon',
                'keywords' => 'refreshing,natural,sweet,tropical',
                'recommendation_reason' => 'A refreshing tropical street drink perfect for hot Vietnamese weather',
                'price_vnd' => 25000,
                'image_path' => 'menu/sugarcane-juice.png',
            ],
        ])->each(function (array $food, int $index): void {
            $food = [
                ...$food,
                ...$this->localizedMenuDetails()[$food['menu_code']],
            ];

            Food::updateOrCreate(
                ['menu_code' => $food['menu_code']],
                [
                    ...$food,
                    'slug' => str($food['name'])->slug()->toString(),
                    'is_available' => true,
                    'sort_order' => $index + 1,
                ],
            );
        });
    }

    /**
     * @return array<string, array{
     *     ingredients: array<int, array{name: string, vietnamese_name: string, quantity_grams: int}>,
     *     taste: FoodTaste,
     *     how_made: string,
     *     vietnamese_how_made: string
     * }>
     */
    private function localizedMenuDetails(): array
    {
        return [
            'pho_bo_01' => [
                'ingredients' => [
                    ['name' => 'Rice noodles', 'vietnamese_name' => 'Bánh phở', 'quantity_grams' => 180],
                    ['name' => 'Beef', 'vietnamese_name' => 'Thịt bò', 'quantity_grams' => 90],
                    ['name' => 'Beef broth', 'vietnamese_name' => 'Nước dùng bò', 'quantity_grams' => 350],
                    ['name' => 'Fresh herbs', 'vietnamese_name' => 'Rau thơm', 'quantity_grams' => 20],
                    ['name' => 'Bean sprouts', 'vietnamese_name' => 'Giá đỗ', 'quantity_grams' => 35],
                ],
                'taste' => FoodTaste::Normal,
                'how_made' => 'Beef bones and aromatics are simmered into broth, then poured over rice noodles, sliced beef, herbs, and sprouts.',
                'vietnamese_how_made' => 'Xương bò và gia vị được hầm thành nước dùng rồi chan lên bánh phở, thịt bò, rau thơm và giá.',
            ],
            'banh_mi_01' => [
                'ingredients' => [
                    ['name' => 'Baguette', 'vietnamese_name' => 'Bánh mì', 'quantity_grams' => 95],
                    ['name' => 'Pork', 'vietnamese_name' => 'Thịt heo', 'quantity_grams' => 80],
                    ['name' => 'Pate', 'vietnamese_name' => 'Pa tê', 'quantity_grams' => 25],
                    ['name' => 'Pickled vegetables', 'vietnamese_name' => 'Đồ chua', 'quantity_grams' => 45],
                    ['name' => 'Cucumber and herbs', 'vietnamese_name' => 'Dưa leo và rau thơm', 'quantity_grams' => 30],
                ],
                'taste' => FoodTaste::Normal,
                'how_made' => 'A crisp baguette is split and filled with pate, pork, pickles, cucumber, herbs, and savory sauce.',
                'vietnamese_how_made' => 'Bánh mì giòn được kẹp pa tê, thịt heo, đồ chua, dưa leo, rau thơm và nước sốt mặn mà.',
            ],
            'bun_bo_hue_01' => [
                'ingredients' => [
                    ['name' => 'Round rice noodles', 'vietnamese_name' => 'Bún sợi to', 'quantity_grams' => 190],
                    ['name' => 'Beef', 'vietnamese_name' => 'Thịt bò', 'quantity_grams' => 100],
                    ['name' => 'Spicy lemongrass broth', 'vietnamese_name' => 'Nước dùng sả cay', 'quantity_grams' => 380],
                    ['name' => 'Fresh herbs', 'vietnamese_name' => 'Rau thơm', 'quantity_grams' => 25],
                    ['name' => 'Chili oil', 'vietnamese_name' => 'Dầu ớt', 'quantity_grams' => 10],
                ],
                'taste' => FoodTaste::Spicy,
                'how_made' => 'A rich beef and lemongrass broth is seasoned with chili oil and served with noodles, beef, and herbs.',
                'vietnamese_how_made' => 'Nước dùng bò sả được nêm dầu ớt rồi dùng với bún, thịt bò và rau thơm.',
            ],
            'mi_quang_01' => [
                'ingredients' => [
                    ['name' => 'Turmeric rice noodles', 'vietnamese_name' => 'Mì nghệ', 'quantity_grams' => 180],
                    ['name' => 'Pork', 'vietnamese_name' => 'Thịt heo', 'quantity_grams' => 85],
                    ['name' => 'Pork broth', 'vietnamese_name' => 'Nước dùng heo', 'quantity_grams' => 180],
                    ['name' => 'Fresh herbs', 'vietnamese_name' => 'Rau sống', 'quantity_grams' => 35],
                    ['name' => 'Peanuts', 'vietnamese_name' => 'Đậu phộng', 'quantity_grams' => 15],
                ],
                'taste' => FoodTaste::Normal,
                'how_made' => 'Turmeric noodles are topped with pork, herbs, peanuts, and a small ladle of concentrated broth.',
                'vietnamese_how_made' => 'Mì nghệ được xếp cùng thịt heo, rau sống, đậu phộng và một ít nước dùng đậm vị.',
            ],
            'com_tam_01' => [
                'ingredients' => [
                    ['name' => 'Broken rice', 'vietnamese_name' => 'Cơm tấm', 'quantity_grams' => 220],
                    ['name' => 'Grilled pork', 'vietnamese_name' => 'Sườn nướng', 'quantity_grams' => 120],
                    ['name' => 'Egg', 'vietnamese_name' => 'Trứng', 'quantity_grams' => 55],
                    ['name' => 'Fish sauce dressing', 'vietnamese_name' => 'Nước mắm', 'quantity_grams' => 35],
                    ['name' => 'Pickled vegetables', 'vietnamese_name' => 'Đồ chua', 'quantity_grams' => 40],
                ],
                'taste' => FoodTaste::Normal,
                'how_made' => 'Broken rice is steamed and plated with marinated grilled pork, egg, pickles, and fish sauce dressing.',
                'vietnamese_how_made' => 'Cơm tấm được hấp chín rồi dọn cùng sườn nướng ướp vị, trứng, đồ chua và nước mắm.',
            ],
            'bun_cha_01' => [
                'ingredients' => [
                    ['name' => 'Rice vermicelli', 'vietnamese_name' => 'Bún', 'quantity_grams' => 190],
                    ['name' => 'Grilled pork', 'vietnamese_name' => 'Thịt heo nướng', 'quantity_grams' => 120],
                    ['name' => 'Dipping sauce', 'vietnamese_name' => 'Nước chấm', 'quantity_grams' => 120],
                    ['name' => 'Fresh herbs', 'vietnamese_name' => 'Rau thơm', 'quantity_grams' => 35],
                    ['name' => 'Pickled vegetables', 'vietnamese_name' => 'Đồ chua', 'quantity_grams' => 30],
                ],
                'taste' => FoodTaste::Normal,
                'how_made' => 'Pork patties and slices are grilled, then served with vermicelli, herbs, pickles, and warm dipping sauce.',
                'vietnamese_how_made' => 'Chả và thịt heo được nướng thơm rồi dùng với bún, rau thơm, đồ chua và nước chấm ấm.',
            ],
            'hu_tieu_01' => [
                'ingredients' => [
                    ['name' => 'Rice noodles', 'vietnamese_name' => 'Sợi hủ tiếu', 'quantity_grams' => 180],
                    ['name' => 'Pork', 'vietnamese_name' => 'Thịt heo', 'quantity_grams' => 75],
                    ['name' => 'Seafood broth', 'vietnamese_name' => 'Nước dùng hải sản', 'quantity_grams' => 350],
                    ['name' => 'Shrimp', 'vietnamese_name' => 'Tôm', 'quantity_grams' => 45],
                    ['name' => 'Fresh herbs', 'vietnamese_name' => 'Rau thơm', 'quantity_grams' => 25],
                ],
                'taste' => FoodTaste::Normal,
                'how_made' => 'Clear pork and seafood broth is ladled over noodles with pork, shrimp, and fresh herbs.',
                'vietnamese_how_made' => 'Nước dùng trong từ heo và hải sản được chan lên hủ tiếu cùng thịt heo, tôm và rau thơm.',
            ],
            'ca_phe_sua_da_01' => [
                'ingredients' => [
                    ['name' => 'Dark coffee', 'vietnamese_name' => 'Cà phê đen', 'quantity_grams' => 80],
                    ['name' => 'Condensed milk', 'vietnamese_name' => 'Sữa đặc', 'quantity_grams' => 35],
                    ['name' => 'Ice', 'vietnamese_name' => 'Đá', 'quantity_grams' => 140],
                ],
                'taste' => FoodTaste::Sweet,
                'how_made' => 'Dark coffee is brewed through a phin over condensed milk, stirred, and poured over ice.',
                'vietnamese_how_made' => 'Cà phê đậm được pha phin trên sữa đặc, khuấy đều rồi rót lên đá.',
            ],
            'bac_xiu_01' => [
                'ingredients' => [
                    ['name' => 'Milk', 'vietnamese_name' => 'Sữa tươi', 'quantity_grams' => 140],
                    ['name' => 'Condensed milk', 'vietnamese_name' => 'Sữa đặc', 'quantity_grams' => 35],
                    ['name' => 'Dark coffee', 'vietnamese_name' => 'Cà phê đen', 'quantity_grams' => 45],
                    ['name' => 'Ice', 'vietnamese_name' => 'Đá', 'quantity_grams' => 130],
                ],
                'taste' => FoodTaste::Sweet,
                'how_made' => 'Milk and condensed milk are mixed with a small pour of strong coffee and served over ice.',
                'vietnamese_how_made' => 'Sữa tươi và sữa đặc được pha với một phần cà phê đậm rồi dùng với đá.',
            ],
            'tra_sua_tran_chau_01' => [
                'ingredients' => [
                    ['name' => 'Milk tea', 'vietnamese_name' => 'Trà sữa', 'quantity_grams' => 260],
                    ['name' => 'Tapioca pearls', 'vietnamese_name' => 'Trân châu', 'quantity_grams' => 70],
                    ['name' => 'Syrup', 'vietnamese_name' => 'Siro đường', 'quantity_grams' => 25],
                    ['name' => 'Ice', 'vietnamese_name' => 'Đá', 'quantity_grams' => 120],
                ],
                'taste' => FoodTaste::Sweet,
                'how_made' => 'Tea is blended with milk and syrup, shaken with ice, and served with chewy tapioca pearls.',
                'vietnamese_how_made' => 'Trà được pha với sữa và siro, lắc cùng đá rồi dùng với trân châu dai.',
            ],
            'matcha_latte_01' => [
                'ingredients' => [
                    ['name' => 'Milk', 'vietnamese_name' => 'Sữa tươi', 'quantity_grams' => 230],
                    ['name' => 'Matcha', 'vietnamese_name' => 'Bột matcha', 'quantity_grams' => 5],
                    ['name' => 'Syrup', 'vietnamese_name' => 'Siro đường', 'quantity_grams' => 25],
                    ['name' => 'Ice', 'vietnamese_name' => 'Đá', 'quantity_grams' => 120],
                ],
                'taste' => FoodTaste::Sweet,
                'how_made' => 'Matcha is whisked smooth, mixed with milk and light syrup, and served cold over ice.',
                'vietnamese_how_made' => 'Matcha được khuấy mịn, pha với sữa và siro nhẹ rồi dùng lạnh với đá.',
            ],
            'nuoc_mia_01' => [
                'ingredients' => [
                    ['name' => 'Fresh sugarcane juice', 'vietnamese_name' => 'Nước mía tươi', 'quantity_grams' => 300],
                    ['name' => 'Kumquat juice', 'vietnamese_name' => 'Nước tắc', 'quantity_grams' => 15],
                    ['name' => 'Ice', 'vietnamese_name' => 'Đá', 'quantity_grams' => 130],
                ],
                'taste' => FoodTaste::Sweet,
                'how_made' => 'Sugarcane is pressed fresh, brightened with kumquat juice, and served immediately over ice.',
                'vietnamese_how_made' => 'Mía được ép tươi, thêm chút tắc cho thơm rồi dùng ngay với đá.',
            ],
        ];
    }
}
